okta:
  oauth2:
    issuer: https://dev-ugadnr0ui0vziqee.us.auth0.com
    client-id: FPH38Y9a40eHs5XSsH7CEioZlnauTXiG
    client-secret: xN7URx_j4yn9Nd22gmGctACeyCCj7nMYYSNKOdsQPXEsEvjHFBanOgSNfFCWScfz

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ugadnr0ui0vziqee.us.auth0.com    # must exactly match Auth0’s “iss” claim :contentReference[oaicite:1]{index=1}
          # jwk-set-uri: https://dev-ugadnr0ui0vziqee.us.auth0.com/.well-known/jwks.json
  # 3) Disable OAuth2 Client auto-configuration (we only need JWT validation)
  autoconfigure:
    exclude:
        - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration  # correct path :contentReference[oaicite:0]{index=0}
  flyway:
    clean-disabled: false

# 4) Your API port
server:
  port: 8080
